name: Watchover
version: '2.0'
main: fr.yabrich.watchover.Main
api-version: '1.21'
authors: [ Yabrich ]
website: https://github.com/Yabrich/Watchover
description: Plugin de modération
softdepend:
  - LuckPerms
  - Essentials
commands:
  vanish:
    description: Active l'invisibilité pour les autres joueurs.
    permission: wo.vanish
    aliases: [wovanish]
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  staffvanish:
    description: Active l'invisibilité pour les autres staffs/joueurs.
    permission: wo.staffvanish
    aliases: [sv]
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  nv:
    description: Active la vision nocturne.
    permission: wo.nightvision
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  spawn:
    description: Téléporte au spawn.
    permission: wo.spawn
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  id:
    description: Donne des informations sur l'item tenu en main.
    permission: wo.id
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  s:
    description: Téléporte un joueur à sa position.
    permission: wo.s
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  wo:
    description: Passe en mode modération.
    permission: wo.watchover
  alert:
    description: Envoie une alerte modération à un joueur.
    permission: wo.alert
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  freeze:
    description: Empêche un joueur de bouger.
    permission: wo.freeze
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  spycmd:
    description: Affiche les commandes executées.
    aliases: [cmdspy]
    permission: wo.spycmd
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  track:
    description: Affiche la position relative d'un joueur sur l'action bar.
    permission: wo.track
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  playerxyz:
    description: Affiche les coordonnées d'un joueur.
    permission: wo.playerxyz
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  chatclear:
    description: Clear le chat.
    permission: wo.chat
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
    aliases: [cc]
  chat:
    description: Modération chat.
    permission: wo.chat
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  helpme:
    description: Aide modération.
    permission: wo.helpme
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  ans:
    description: Réponds à une question.
    permission: wo.helpme.ans
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  report:
    description: Signalement de joueur.
    permission: wo.report
    permission-message: §4Vous n'avez pas la permission d'effectuer cette commande !
  staffchat:
    description: Chat staff.
    permission: wo.staffchat
    aliases: [sc]