name: Watchover
version: '2.0-SNAPSHOT'
main: fr.yabrich.watchover.Main
api-version: '1.21'
authors: [ Yabrich ]
commands:
  vanish:
    description: Active l'invisibilité pour les autres joueurs.
    permission: wo.vanish
    aliases: [wovanish]
  nv:
    description: Active la vision nocturne.
    permission: wo
  spawn:
    description: Téléporte au spawn.
    permission: wo
  id:
    description: Donne des informations sur l'item tenu en main.
    permission: wo
  s:
    description: Téléporte un joueur à sa position.
    permission: wo
  wo:
    description: Passe en mode modération.
    permission: wo
  alert:
    description: Envoie une alerte modération à un joueur.
    permission: wo
  freeze:
    description: Empêche un joueur de bouger.
    permission: wo
  spycmd:
    description: Affiche les commandes executées.
    aliases: [cmdspy]
    permission: wo
  fakeleave:
    description: Simule la déconnexion du serveur pour les autres joueurs.
    permission: wo.vanish
    aliases: [fl]
  track:
    description: Affiche la position relative d'un joueur sur l'action bar.
    permission: wo.track
